version: "3.8"

volumes:
  db_data:
  user-db_data:

networks:
  traefik-net:
    driver: bridge

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--metrics.prometheus=true"  
    ports:
      - "81:80"
      - "8081:8080"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net

  establecimientos-db:
    image: fyjo/monosgps-establecimientos-db:latest
    container_name: establecimientos-db
    environment:
      POSTGRES_USER: monos
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: establecimientos
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - traefik-net

  user-db:
    image: fyjo/monosgps-usuarios-db:latest
    container_name: user-db
    environment:
      POSTGRES_USER: monos
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usuarios
    volumes:
      - user-db_data:/var/lib/postgresql/data
    networks:
      - traefik-net

  auth-service:
    image: fyjo/monosgps-authservice:latest
    container_name: auth-service
    depends_on:
      - user-db
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.rule=PathPrefix(`/AuthService`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8081"

  buscarpersonas:
    image: fyjo/monosgps-buscarpersonas:latest
    container_name: buscarpersonas
    depends_on:
      - establecimientos-db
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.personas.rule=PathPrefix(`/api`)"
      - "traefik.http.services.personas.loadbalancer.server.port=8082"

  frontend:
    image: fyjo/monosgps-frontend:latest
    container_name: frontend
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  prometheus:
    image: prom/prometheus
    container_name: prometheusMonos
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.rules:/etc/prometheus/alerts.rules
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9091:9091"
    networks:
      - traefik-net

  grafana:
    image: grafana/grafana
    container_name: grafanaMonos
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/all.yaml
    ports:
      - "82:3000"
    networks:
      - traefik-net

    
