global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'buscarpersonas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['buscarpersonas:8082']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafanaMonos:3000']