global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'docker-services'
    static_configs:
      - targets:
          - auth-service:8081
          - buscarpersonas:8082
          - frontend:80
