name: CD BuscarPersonas

on:
  workflow_run:
    workflows: ["Build and Push BuscarPersonas"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BuscarPersonas via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /ruta/al/proyecto/docker-compose
            docker-compose pull buscarpersonas
            docker-compose up -d buscarpersonas