name: CD DB Establecimientos

on:
  workflow_run:
    workflows: ["Build & Push DB Establecimientos"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Establecimientos DB via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash -lc "cd /home/${{ secrets.SERVER_USER }}/proyecto && docker-compose pull establecimientos-db && docker-compose up -d establecimientos-db"
