name: CD materialesService

on:
  workflow_run:
    workflows: ["Build and Push materialesService"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy materialesService via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash -lc "cd /home/${{ secrets.SERVER_USER }}/proyecto && docker-compose pull materiales-service && docker-compose up -d materiales-service"
      
