name: Deploy Docker Compose

on:
  workflow_dispatch:
  push:
    paths:
      - "docker-compose.yaml"
      - "Monitoring/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # Verifica que el archivo existe localmente en el repo
      - name: Verificar archivo prometheus.yaml localmente
        run: |
          if [ -f Monitoring/prometheus.yaml ]; then
            echo "✅ prometheus.yaml encontrado localmente"
          else
            echo "❌ Error: Monitoring/prometheus.yaml no existe"
            exit 1
          fi

      # Copiar docker-compose.yaml al servidor
      - name: Copiar docker-compose.yaml al servidor
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.SERVER_USER }}/proyecto"

      # Crear carpeta Monitoring si no existe
      - name: Crear carpeta Monitoring en el servidor
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.SERVER_USER }}/proyecto/Monitoring

      # Eliminar carpeta prometheus.yaml si existe
      - name: Eliminar carpeta prometheus.yaml si fue creada por error
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ -d "/home/${{ secrets.SERVER_USER }}/proyecto/Monitoring/prometheus.yaml" ]; then
              echo "🧹 Eliminando carpeta conflictiva prometheus.yaml"
              rm -r "/home/${{ secrets.SERVER_USER }}/proyecto/Monitoring/prometheus.yaml"
            fi

      # Copiar prometheus.yaml al servidor (ruta corregida)
      - name: Copiar prometheus.yaml al servidor
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Monitoring/prometheus.yaml"
          target: "/home/${{ secrets.SERVER_USER }}/proyecto/Monitoring"

      # Verificar que prometheus.yaml en el servidor sea un archivo
      - name: Verificar que prometheus.yaml es un archivo
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ -f "/home/${{ secrets.SERVER_USER }}/proyecto/Monitoring/prometheus.yaml" ]; then
              echo "prometheus.yaml es un archivo válido"
            else
              echo "Error: prometheus.yaml no es un archivo o no existe"
              exit 1
            fi

      # Levantar contenedores en el servidor
      - name: Ejecutar docker-compose en el servidor
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/proyecto
            docker-compose pull
            docker-compose up -d
