name: Deploy Docker Compose

on:
  workflow_dispatch:
  push:
    paths:
      - "docker-compose.yaml" 
      - "Monitoring/prometheus.yaml"  # <-- Corregido con mayúscula
              
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar archivos en el runner (debug)
        run: |
          echo "Archivos en el directorio raíz:"
          ls -al
          echo "Archivos en la carpeta Monitoring:"
          ls -al Monitoring

      - name: Copiar docker-compose.yaml al servidor
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.SERVER_USER }}/proyecto"   

      - name: Crear directorio Monitoring en el servidor si no existe
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.SERVER_USER }}/proyecto/Monitoring
  
      - name: Copiar prometheus.yaml al servidor
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Monitoring/prometheus.yaml"  # <-- Corregido con mayúscula
          target: "/home/${{ secrets.SERVER_USER }}/proyecto/Monitoring"     

      - name: Ejecutar docker-compose en el servidor
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/proyecto
            docker-compose pull
            docker-compose up -d
