name: Deploy Docker Compose

on:
  workflow_dispatch:
  push:
    paths:
      - "docker-compose.yaml" 
              
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copiar docker-compose.yaml al servidor
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.SERVER_USER }}/proyecto"

      - name: Ejecutar docker-compose en el servidor
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/proyecto
            docker-compose pull
            docker-compose up -d
